name: Dispatch Update Submodule

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [
      # CONFIGURAÇÕES DO SITE
      "**/*.css",
      "**/*.html",
      "**/*.js",
      # CONFIGURAÇÕES DO REPOSITÓRIO
      "**/*.yml",
      "**/*.yaml",
      "**/*.bib",
      "**/*.qmd",
      "**/*.md",
      "**/*.json",
      "**/*.Rmd",
      "**/*.R",
      ]

permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENTS
    env:
      TOKEN: ${{ secrets.UPDATE_SUBMODULE }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Atualizar 'submódulo books'
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ${{ env.USERNAME }}/estatistica
          token: ${{ env.TOKEN }}
          event-type: atualizar-books

      - name: Mensagem sucesso
        run: echo "Disparo realizado com sucesso!"
# referências:
# - https://medium.com/@0xWerz/how-to-automatically-update-git-submodules-using-github-actions-d71c8126e82e
