name: "[build] - Renderizar Books Quarto"

on:
  workflow_dispatch:
  push:
    branches: [main, dev1]
    paths: ["build/**/*.qmd", "build/**/*.yml"]
  pull_request:
    branches: [main, dev1]
    paths: ["build/**/*.qmd", "build/**/*.yml"]

permissions:
  contents: write
  pull-requests: read
  pages: write
  id-token: write

jobs:
  evento:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      EVENTO: ${{ steps.tipo_evento.outputs.evento }}
    steps:
      - name: Verificar tipo de evento
        id: tipo_evento
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "evento=dispatch" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "evento=pull" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "evento=push" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "merge_group" ]]; then
            echo "evento=mergegroups" >> $GITHUB_OUTPUT
          else
            echo "evento=outro" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT  

  detectar:
    runs-on: ubuntu-latest
    needs: [evento]
    environment:
      name: ENVIRONMENT
    env:
      REPO_SYNC: ${{ secrets.REPO_SYNC }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
      TIPO_EVENTO: ${{ needs.evento.outputs.EVENTO }}
    outputs:
      FOLDERS_LISTA: ${{ steps.lista.outputs.folders_lista }}
    steps:
      - name: Clona o Repositório BOOKS
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME  }}/books
          token: ${{ secrets.REPO_SYNC }}
          path: books
          ref: main
          fetch-depth: 2

      - name: Lista Estrutura do Workspace
        run: |
          echo "Estrutura do workspace:"
          ls books

      - name: Identificar arquivos alterados
        id: arquivos-alterados
        run: |
          cd books
          echo "Verificando o tipo de evento: $TIPO_EVENTO"
          if [[ "$TIPO_EVENTO" == "pull" ]]; then
            gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[].filename' > arquivos.txt
          elif [[ "$TIPO_EVENTO" == "push" ]]; then
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > arquivos.txt
          else
            git ls-files | grep -E '^build/.*\.(qmd|yml)$' > arquivos.txt
          fi
          echo "Arquivos detectados:"
          cat arquivos.txt || true
          if [ ! -s arquivos.txt ]; then
            echo "AVISO: Nenhum arquivo alterado foi detectado para o evento $TIPO_EVENTO"
          fi

      - name: Extrair nomes de subdiretórios dos arquivos alterados
        id: extrair_subdirs
        run: |
          cd books
          echo "Arquivos encontrados:"
          cat arquivos.txt || true
          FILES_NAMES=$(cat arquivos.txt)
          if [ -z "$FILES_NAMES" ]; then
            echo "AVISO: arquivos.txt está vazio, nenhum diretório será listado!"
          fi
          echo "$FILES_NAMES" | grep -oE '^build/([A-Z]{3}[0-9]{4})/' || echo "Nenhum diretório encontrado pelo grep"
          echo "$FILES_NAMES" | grep -oE '^build/([A-Z]{3}[0-9]{4})/' | cut -d'/' -f2 > subdirs.txt

      - name: Montar lista única de subdiretórios e exportar output
        id: lista
        run: |
          cd books
          FOLDERS_NAMES=$(cat subdirs.txt | sort | uniq | xargs)
          echo "Exibindo subdiretórios alterados: $FOLDERS_NAMES"
          echo "folders_lista=$FOLDERS_NAMES" >> $GITHUB_OUTPUT

      - name: Movendo livros detectados para _books
        if: steps.lista.outputs.folders_lista != ''
        env:
          FOLDERS_LISTA: ${{ steps.lista.outputs.folders_lista }}
        run: |
          cd books
          mkdir -p ../_books
          for folder in $FOLDERS_LISTA; do
            if [ -d "build/${folder}" ]; then
              mv "build/${folder}" ../_books/
            else
              echo "Diretório build/${folder} não encontrado!"
            fi
          done

      # Exclusão antes do upload, se desejar garantir limpeza (opcional, mas não necessário pois nome é único)
      # - name: Excluir artefato antigo books_detectados
      #   uses: GeekyEggo/delete-artifact@v5
      #   with:
      #     name: books_detectados

      - name: Exportar lista de livros alterados
        uses: actions/upload-artifact@v4
        with:
          name: books_detectados
          path: _books

  renderizar:
    needs: [detectar]
    runs-on: ubuntu-latest
    if: needs.detectar.outputs.FOLDERS_LISTA != ''
    environment:
      name: ENVIRONMENT
    env:
      REPO_SYNC: ${{ secrets.REPO_SYNC }}
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    outputs:
      BOOKS_RENDERIZADOS: ${{ steps.renderizar.outputs.books_renderizados }}

    steps:
      - name: Baixar artefato com lista de livros alterados
        uses: actions/download-artifact@v4
        with:
          name: books_detectados
          path: "_books"

      # Excluir artefato antigo ANTES do upload do novo books_renderizados
      - name: Excluir artefato antigo books_renderizados
        uses: GeekyEggo/delete-artifact@v5
        with:
          name: books_renderizados

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar livros Quarto
        env:
          FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
        run: |
          cd _books
          echo "$FOLDERS_LISTA" | tr ' ' '\n' | while read folder; do
            if [ -d "${folder}" ]; then
              echo "Renderizando livro: $folder"
              quarto render "${folder}" --to html --execute
            else
              echo "Diretório ${folder} não encontrado!"
            fi
          done

      - name: Excluindo pastas '**/delete'
        run: |
          if [ -d "docs/delete" ]; then
            echo "Excluindo diretório 'delete'..."
            rm -rf docs/delete
          fi

      - name: Exibindo livros renderizados
        run: |
          books=$(find docs -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | xargs)
          echo "books_renderizados=$books" >> $GITHUB_OUTPUT

      - name: Exportar livros renderizados
        uses: actions/upload-artifact@v4
        with:
          name: books_renderizados
          path: docs

  backend:
    needs: [renderizar]
    runs-on: ubuntu-latest
    if: needs.detectar.outputs.FOLDERS_LISTA != ''
    environment:
      name: ENVIRONMENT
    env:
      REPO_SYNC: ${{ secrets.REPO_SYNC }}
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Clona o Repositório BACKEND
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME  }}/backend
          token: ${{ secrets.REPO_SYNC }}
          path: backend
          ref: main

      - name: Instalar pacote backend
        run: |
          set -e
          pip install -e backend

      - name: Baixar artefatos BOOKS RENDERIZADOS
        uses: actions/download-artifact@v4
        with:
          name: books_renderizados
          path: ./backend/_books/

      # Excluir artefato antigo ANTES do upload do novo books_backend
      - name: Excluir artefato antigo books_backend
        uses: GeekyEggo/delete-artifact@v5
        with:
          name: books_backend

      - name: Automação de livros (backend)
        id: backend_books
        run: |
          set -e
          python backend/test/renderbook.py 2>&1 | tee backend_output.log
          if grep -i "warning\|error" backend_output.log; then
            echo "Erros ou warnings detectados durante a execução do script!"
            exit 1
          fi

      - name: Exporta atualizações dos livros renderizados
        uses: actions/upload-artifact@v4
        with:
          name: books_backend
          path: backend/_books

  artefato:
    needs: [backend]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Checkout da branch books
        uses: actions/checkout@v4
        with:
          ref: books
          fetch-depth: 0

      - name: Baixar artefato dos livros renderizados
        uses: actions/download-artifact@v4
        with:
          name: books_backend
          path: _books

      - name: Sincronizar arquivos do artefato com a branch books
        run: |
          rsync -av --delete _books/ ./

      - name: Salvar artefato completo para deploy
        uses: actions/upload-artifact@v4
        with:
          name: artefato_completo
          path: "."

  pages:
    needs: [artefato]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    steps:
      - name: Baixar artefato completo para deploy
        uses: actions/download-artifact@v4
        with:
          name: artefato_completo
          path: _site

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: "_site"

  estatistica:
    needs: [ artefato ]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
      USERNAME: ${{ github.repository_owner }}
      USEREMAIL: ${{ secrets.USEREMAIL }} 
      REPO_SYNC: ${{ secrets.REPO_SYNC }}
    steps:
      - name: Clona o Repositório ESTATISTICA
        uses: actions/checkout@v4
        with:
          ref: books
          path: estatistica
          fetch-depth: 0
          repository: ${{ env.USERNAME }}/estatistica
          token: ${{ secrets.REPO_SYNC }}

      - name: Baixar artefato dos livros renderizados
        uses: actions/download-artifact@v4
        with:
          name: artefato_completo
          path: _books

      - name: Garante que a branch books existe e faz checkout
        working-directory: estatistica
        run: |
          if ! git rev-parse --verify books >/dev/null 2>&1; then
            git checkout --orphan books
            git rm -rf .
            git commit --allow-empty -m "Cria branch books inicial"
            git push origin books
          else
            git checkout books
          fi

      - name: Sincronizar arquivos do artefato com a branch books
        run: |
          rsync -av --delete _books/ estatistica/books/

      - name: Configura credenciais do Git
        working-directory: estatistica
        run: |
          git config user.name "${{ env.USERNAME }}"
          git config user.email "${{ env.USEREMAIL }}"
          git remote set-url origin https://x-access-token:${{ env.REPO_SYNC }}@github.com/${{ env.USERNAME }}/estatistica.git

      - name: Commit e Push dos livros renderizados
        working-directory: estatistica
        run: |
          git add books/
          git commit -m "books: atualiza books a partir do repo:books" || echo "Nada a commitar"
          git push --force origin books