# Código gerado/assistido por IA
name: Notifica books para atualizar submodule

on:
  push:
    branches: [main]
    paths: ["books/**/*.qmd", "books/**/*.yml", "books/*.html", "books/*.bib"]

jobs:
  notifica-books:
    runs-on: ubuntu-latest
    steps:
      - name: Dispara 'repository_dispatch' no books
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
            https://api.github.com/repos/czargab18/books/dispatches \
            -d '{"event_type": "atualiza-books"}'
