name: render_books
# Descrição: Renderiza livros em Quarto e executa tarefas pós-processamento

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 27 8 *"
  push:
    branches: [main]
    paths:
      - "**/build/*.qmd"
      - "**/build/*.yml"
      - "**/.github/workflows/*book*.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/build/*.qmd"
      - "**/build/*.yml"
      - "**/.github/workflows/*book*.yml"

permissions:
  contents: write
  pages: write
  pull-requests: read

# Reestruturar os Ambientes
# - detect: para detectar subdiretórios modificados
# - build: Adicionar as dependencias:
#          Quarto/cache + Python/cache:backend
# - render: para renderizar os livros
# - clean: para limpar arquivos temporários
# - repo: para gerenciar o repositório e enviar alterações
# - pages: para publicar no GitHub Pages

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      subfolders: ${{ steps.detect-subfolders.outputs.subfolders }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Listar arquivos modificados (preciso)
        id: arquivos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            REPO="${{ github.repository }}"
            FILES=$(curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | jq -r '.[].filename')
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          else
            FILES=$(git ls-files "build/*.qmd" "build/*.yml")
          fi
          echo "Arquivos modificados:"
          echo "$FILES"
          echo "$FILES" > arquivos_modificados.txt

      - name: Identificar subdiretórios correspondentes
        id: detect-subfolders
        run: |
          SUBFOLDERS=$(grep -oE '^build/[A-Z]{3}[0-9]{4}/' arquivos_modificados.txt | cut -d'/' -f2 | sort | uniq | xargs || echo "")
          echo "Subdiretórios detectados: $SUBFOLDERS"
          echo "subfolders=$SUBFOLDERS" >> $GITHUB_OUTPUT

  render:
    needs: [detect]
    runs-on: ubuntu-latest
    if: ${{ needs.detect.outputs.subfolders != '' }}
    env:
      SUBFOLDERS: ${{ needs.detect.outputs.subfolders }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar books (Quarto)
        run: |
          for folder in $SUBFOLDERS; do
            echo "Renderizando build/$folder ..."
            quarto render build/$folder --to html || echo "Falha ao renderizar build/$folder"
          done

      # Opcional: Pós-processamento Python
      # - name: Correções com Python
      #   env:
      #     PYTHONPATH: ./
      #   run: |
      #     for folder in $SUBFOLDERS; do
      #       echo "Processando build/$folder com Python..."
      #       # python -m backend.tasks.books.renderbook build/$folder
      #     done

  clean:
    needs: [render]
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Excluir arquivos gerados pelo Quarto
        run: |
          set -e
          for dir in delete ac; do
            if [ -d "$dir" ]; then
              echo "Excluindo diretório '$dir'..."
              rm -rf "$dir"
            else
              echo "Diretório '$dir' não encontrado."
            fi
          done

  repo:
    needs: [render, clean]
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Configurar usuário do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Adicionar e commitar alterações
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "chore: atualizações automáticas dos livros renderizados [ci skip]"
          fi

      - name: Enviar alterações para o GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
          fi
