# Variáveis de ambiente (env):
# GITHUB_TOKEN
# GITHUB_TOKEN
# TIPO_EVENTO
# SUBFOLDERS
# BOOKS_RENDER
# USERNAME
# USEREMAIL
# Outputs e variáveis criadas por steps:
# steps.detect-subfolders.outputs.subfolders
# steps.tipo_evento.outputs.tipo_event
# steps.render_books.outputs.books_render
# needs.detectar.outputs.subfolders
# needs.renderizar.outputs.books_render
# Parâmetros especiais do GitHub:
# github.event_name
# github.repository
# github.event.pull_request.number
# github.event.before
# github.sha



name: "[build] Renderizar Books Quarto"

permissions:
  contents: write
  pull-requests: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ secrets.USERNAME }}
  USEREMAIL: ${{ secrets.USEREMAIL }}


on:
  workflow_dispatch:
  push:
    branches: [main, dev1]
    paths:
      - "build/*.qmd"
      - "build/*.yml"
  pull_request:
    branches: [main, dev1]
    paths:
      - "build/*.qmd"
      - "build/*.yml"

jobs:
  detectar:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      subfolders: ${{ steps.detect-subfolders.outputs.subfolders }}

    steps: 
      - name: Checar o repositório 
        uses: actions/checkout@v4

      - name: Verificar tido evento
        id: tipo_evento
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Evento: Dispatch Manual"
            echo "tipo_event=dispatch" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Evento: Pull Request"
            echo "tipo_event=pull" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Evento: Push"
            echo "tipo_event=push" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "merge_group" ]]; then
            echo "Evento: Merge Group"
            echo "tipo_event=mergegroups" >> $GITHUB_OUTPUT
          else
            echo "Evento: Outros"
            echo "tipo_event=outro" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - name: Identificar arquivos alterados
        id: arquivos-alterados
        env:
          TIPO_EVENTO: ${{ steps.tipo_evento.outputs.tipo_event }}
        run: |
          if [[ "${TIPO_EVENTO}" == "pull" ]]; then
            gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[].filename' > arquivos.txt
          elif [[ "${TIPO_EVENTO}" == "push" ]]; then
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > arquivos.txt
          elif [[ "${TIPO_EVENTO}" == "mergegroups" ]]; then
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > arquivos.txt
          elif [[ "${TIPO_EVENTO}" == "dispatch" ]]; then
            git ls-files "build/*.qmd" "build/*.yml" > arquivos.txt
          else
            git ls-files "build/*.qmd" "build/*.yml" > arquivos.txt
          fi

      - name: Identificar subdiretórios correspondentes
        id: detect-subfolders
        run: |
          set -e
          FILES=$(cat arquivos.txt)
          SUBFOLDERS=$(echo "$FILES" | grep -oE '^build/([A-Z]{3}[0-9]{4})/' | cut -d'/' -f2 | sort | uniq | xargs)
          echo "Subdiretórios detectados: $SUBFOLDERS"
          echo "subfolders=$SUBFOLDERS" >> $GITHUB_OUTPUT

  renderizar:
    needs: [detectar]
    runs-on: ubuntu-latest
    env:
      SUBFOLDERS: ${{ needs.detectar.outputs.subfolders }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar Livros Quarto
        id: render_books
        run: |
          if [ -z "$SUBFOLDERS" ]; then
            echo "Nenhum subdiretório encontrado. Abortando renderização."
            exit 0
          fi
          echo "Iniciando renderização dos livros..."
          for folder in $SUBFOLDERS; do
            echo "Renderizando build/$folder ..."
            quarto render build/$folder --to html || echo "Falha ao renderizar build/$folder"
          done
          echo "books_render=docs" >> $GITHUB_OUTPUT

  backend:
    needs: [detectar, renderizar]
    runs-on: ubuntu-latest
    env:
      REPO_SYNC: ${{ secrets.REPO_SYNC }}
    outputs:
      docs_books_render: ${{ steps.render_books.outputs.books_render }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Clonar o repo:backend
        uses: actions/checkout@v4
        with:
          repository: czargab18/backend
          token: ${{ secrets.REPO_SYNC }}
          path: backend
          ref: main

      - name: Instalar pacote backend
        run: |
          set -e
          pip install -e ./backend

      # - name: adicion link_books a lista em ./index.html
      #   run: echo "Em desenvolvido"

      # - name: adicion link_books a lista em ./index.html
      #   run: python backend/scripts/add_link_books.py

      # - name: Corrigindo links de <head> dos books (com backend)
      #   run: python backend/scripts/corrigir_links.py

  formatar:
    needs: [renderizar, backend]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOOKS_RENDER: ${{ needs.renderizar.outputs.books_render }}
    outputs:
      DOCS_BOOKS_RENDER: ${{ steps.format.outputs.books_render }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Instalar Prettier
        run: npm install -g prettier

      - name: Formatar arquivos HTML, CSS e JS
        id: format
        run: |
          if [ -d "${{ env.BOOKS_RENDER }}" ]; then
            prettier --write "${{ env.BOOKS_RENDER }}/**/*.{html,css,js}"
            echo "books_render=${{ env.BOOKS_RENDER }}" >> $GITHUB_OUTPUT
          else
            echo "Diretório ${{ env.BOOKS_RENDER }} não encontrado. Abortando."
            exit 1
          fi

  repositorio:
    needs: [formatar]
    runs-on: ubuntu-latest
    env:
      BOOKS_RENDER: ${{ needs.renderizar.outputs.books_render }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      USERNAME: ${{ secrets.USERNAME }}
      USEREMAIL: ${{ secrets.USEREMAIL }}

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar usuário do Git
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.USEREMAIL }}"

      - name: Verificar e criar branch "books" se necessário
        run: |
          if ! git show-ref --verify --quiet refs/heads/books; then
            echo "Branch 'books' não existe. Criando..."
            git checkout -b books
          else
            echo "Branch 'books' já existe. Alternando para ela..."
            git checkout books
          fi

      - name: Adicionar e commitar alterações
        run: |
          git add ${{ env.BOOKS_RENDER }}
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "chore: atualiza livros renderizados [ci skip]"
          fi

      - name: Enviar alterações para o GitHub
        run: |
          git push origin books

  estatistica:
    #  mover os arquivos de docs do repo: books , `repo:books/docs`, para a pasta books do repo: estatistica, repo:estatistica/books.
    # Atualizando os arquivos de books/docs em estatistica/books, caso estejam desatualizados, ou adicionando caso não existam em estatistica/books.
    needs: [formatar]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOOKS_RENDER: ${{ needs.renderizar.outputs.books_render }}
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4
