name: "Renderizar Books Quarto"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["build/**/*.qmd", "build/**/*.yml", "build/index.html", "build/ac/*.html"]
  pull_request:
    branches: [ma]
    paths: ["build/**/*.qmd", "build/**/*.yml", "build/index.html", "build/ac/*.html", ]

permissions:
  contents: write
  pull-requests: read
  pages: write
  id-token: write

jobs:
  evento:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      EVENTO: ${{ steps.evento.outputs.evento }}
    steps:
      - name: Verifica tipo de evento
        id: evento
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "evento=dispatch" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "evento=pull" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "evento=push" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "merge_group" ]]; then
            echo "evento=mergegroups" >> $GITHUB_OUTPUT
          else
            echo "evento=outro" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

  detectar:
    runs-on: ubuntu-latest
    needs: [evento]
    environment:
      name: ENVIRONMENT
    env:
      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
      EVENTO: ${{ needs.evento.outputs.EVENTO }}
    outputs:
      FOLDERS_LISTA: ${{ steps.lista.outputs.folders_lista }}
    steps:
      - name: Clona o Repositório BOOKS
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME  }}/books
          token: ${{ secrets.TOKEN_REPO_SYNC }}
          path: books
          ref: main
          fetch-depth: 30

      - name: Identifica arquivos alterados (pull request)
        if: github.event_name == 'pull_request'
        id: arquivos-alterados-pull
        run: |
          cd books
          gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[].filename' > arquivos.txt

      - name: Identifica arquivos alterados (push)
        if: github.event_name == 'push'
        id: arquivos-alterados-push
        run: |
          cd books
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > arquivos.txt

      - name: Identifica arquivos alterados (outros eventos)
        if: (github.event_name != 'pull_request') && (github.event_name != 'push')
        id: arquivos-alterados-outros
        run: |
          cd books
          git ls-files | grep -E '^build/.*\.(qmd|yml)$' > arquivos.txt

      - name: Extrai nomes de subdiretórios dos arquivos alterados
        id: extrair_subdirs
        run: |
          cd books
          FILES_NAMES=$(cat arquivos.txt)
          echo "$FILES_NAMES" | grep -oE '^build/([A-Z]{3}[0-9]{4})/' | cut -d'/' -f2 > subdirs.txt

      - name: Monta lista única de subdiretórios e exporta output
        id: lista
        run: |
          cd books
          FOLDERS_NAMES=$(cat subdirs.txt | sort | uniq | xargs)
          echo "folders_lista=$FOLDERS_NAMES" >> $GITHUB_OUTPUT

      - name: Move livros detectados para _books
        if: steps.lista.outputs.folders_lista != ''
        env:
          FOLDERS_LISTA: ${{ steps.lista.outputs.folders_lista }}
        run: |
          mkdir -p _books
          cd books
          for folder in $FOLDERS_LISTA; do
            if [ -d "build/${folder}" ]; then
              mv "build/${folder}" ../_books/
            fi
          done

      - name: Exporta Books como Artefato
        if: steps.lista.outputs.folders_lista != ''
        uses: actions/upload-artifact@v4
        with:
          name: books_detectados
          path: _books

  renderizar:
    needs: [detectar]
    runs-on: ubuntu-latest
    if: needs.detectar.outputs.FOLDERS_LISTA != ''
    env:
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
    outputs:
      BOOKS_RENDERIZADOS: ${{ steps.renderizar.outputs.books_renderizados }}

    steps:
      - name: Baixa artefato
        uses: actions/download-artifact@v4
        with:
          name: books_detectados
          path: _books

      - name: Configura Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderiza livros Quarto
        env:
          FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
        run: |
          set -e
          cd _books
          echo "$FOLDERS_LISTA" | tr ' ' '\n' | while read folder; do
            if [ -d "${folder}" ]; then
              echo "Renderizando livro: $folder"
              quarto render "${folder}" --to html --execute --output-dir "../../_docs/${folder}"
            else
              echo "Pasta não encontrada: $folder"
            fi
          done

      - name: Limpa diretórios '_docs/ac/site_libs' e '_docs/delete'
        run: |
          cd _docs
          rm -rf ac/site_libs
          rm -rf delete

      - name: Exporta livros renderizados
        uses: actions/upload-artifact@v4
        with:
          name: books_renderizados
          path: "./_docs"

  backend:
    needs: [renderizar]
    runs-on: ubuntu-latest
    if: needs.detectar.outputs.FOLDERS_LISTA != ''
    environment:
      name: ENVIRONMENT
    env:
      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Clona o Repositório BACKEND
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USERNAME  }}/backend
          token: ${{ secrets.TOKEN_REPO_SYNC }}
          path: backend
          ref: main

      - name: Instala pacote backend
        run: |
          set -e
          pip install -e backend

      - name: Baixa artefatos BOOKS RENDERIZADOS
        uses: actions/download-artifact@v4
        with:
          name: books_renderizados
          path: ./backend/_books/

      - name: Automatiza livros (backend)
        id: backend_books
        run: |
          set -e
          python backend/tasks/actionbooks/renderbook.py 2>&1 | tee backend_output.log
          if grep -i "warning\|error" backend_output.log; then
            echo "Erros ou warnings detectados durante a execução do script!"
            exit 1
          fi

      - name: Exporta atualizações dos livros renderizados
        uses: actions/upload-artifact@v4
        with:
          name: books_backend
          path: ./backend/_books/

  sync_artefato:
    needs: [backend]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Checkout da branch 'books'
        uses: actions/checkout@v4
        with:
          ref: books
          path: books
          fetch-depth: 0

      - name: Baixa artefato dos livros renderizados
        uses: actions/download-artifact@v4
        with:
          name: books_backend
          path: _books

      - name: Sincroniza arquivos do artefato com a branch books
        run: |
          rsync -av --update _books/ books/

      - name: Salva Artefato Completo
        uses: actions/upload-artifact@v4
        with:
          name: artefatos_books
          path: "books"

  pages:
    needs: [sync_artefato]
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    steps:
      - name: Baixa Artefato para GitHub Pages
        uses: actions/download-artifact@v4
        with:
          name: artefatos_books
          path: "./"

      - name: Salva Artefato para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: "./"

      - name: Faz deploy para GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

  estatistica:
    needs: [sync_artefato]
    runs-on: ubuntu-latest
    if: needs.detectar.outputs.FOLDERS_LISTA != ''
    environment:
      name: ENVIRONMENT
    env:
      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
      USERNAME: ${{ github.repository_owner }}
      USEREMAIL: ${{ secrets.USEREMAIL }}
      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
    steps:
      - name: Clona o Repositório ESTATISTICA
        uses: actions/checkout@v4
        with:
          ref: book
          path: estatistica
          fetch-depth: 0
          repository: ${{ env.USERNAME }}/estatistica
          token: ${{ secrets.TOKEN_REPO_SYNC }}

      - name: Baixa artefato dos livros renderizados
        uses: actions/download-artifact@v4
        with:
          name: artefatos_books
          path: _books

      - name: Garante que a branch book existe e faz checkout
        working-directory: estatistica
        run: |
          if ! git rev-parse --verify book >/dev/null 2>&1; then
            git checkout --orphan book
            git rm -rf .
            git commit --allow-empty -m "Cria branch book inicial"
            git push origin book
          else
            git checkout book
          fi

      - name: Sincroniza arquivos do artefato com a branch book
        run: |
          rsync -av --update --delete _books/ estatistica/books/

      - name: Configura credenciais do Git
        working-directory: estatistica
        run: |
          git config user.name "${{ env.USERNAME }}"
          git config user.email "${{ env.USEREMAIL }}"
          git remote set-url origin https://x-access-token:${{ env.TOKEN_REPO_SYNC }}@github.com/${{ env.USERNAME }}/estatistica.git

      - name: Faz commit e push dos livros renderizados
        working-directory: estatistica
        run: |
          git add books/
          git commit -m "books: atualiza books a partir do repo:books" || echo "Nada a commitar"
          git push --force origin book

  cleanup:
    needs: [pages, estatistica]
    runs-on: ubuntu-latest
    steps:
      - name: Deleta artefatos
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            github-pages
            books_renderizados
            books_detectados
            books_backend
            artefatos_books
