name: Renderizar Books com Quarto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 16 * 1"
  push:
    branches: [main]
    paths: [
      "**/build/*.qmd",
      "**/build/*.yml",
      "**/.github/workflows/*book*.yml"
    ]
  pull_request:
    branches: [main]
    paths: [
      "**/build/*.qmd",
      "**/build/*.yml",
      "**/.github/workflows/*book*.yml"
    ]
permissions:
  contents: write
  pages: write
  pull-requests: read

jobs:
  # Ideia:
  # - build: configurar dependencias e caches
  # - renderizar Books e salva-los em `/docs/`
  # - apenas enviar os arquivos da pasta /docs/ para repo:estatistica/books/